### ISSUE TITLE
Items under <details> don't render as links on website

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/awesome-inspiration#27]
See https://swapagarwal.github.io/awesome-inspiration/

**Comment by TPS** [comment]
Try like @ https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d#gistcomment-2041319, but YMMV 🤷:
>Markdown's supported, as long as you have a blank line between the </summary> tag and the following content. Apparently kramdown is very sensitive to missing blank lines.

Examples given @ link.

**Comment by swapagarwal** [comment]
@TPS So I have the blank line (see [here](https://raw.githubusercontent.com/swapagarwal/awesome-inspiration/master/README.md)) and it renders correctly on the [README](https://github.com/swapagarwal/awesome-inspiration) but not on the [website](https://swapagarwal.github.io/awesome-inspiration/).

**Comment by TPS** [comment]
Did you contact GitHub support?  Or try direct `<a href=`, since just links?

**Comment by swapagarwal** [comment]
It worked! Thanks a ton @TPS  🎂

**Comment by TPS** [comment]
You're welcome, of course. 😊
