### ISSUE TITLE
geek movies collection

### ISSUE THREAD

**Issue by greybax** [swapagarwal/awesome-inspiration#40]
Your repo is nice! 👍  And as I see you have movie collection here https://github.com/swapagarwal/awesome-inspiration#movies, so I would suggest to add geek movies collection which I'm curating which has lot of films about geeks too. You can see it here: https://github.com/greybax/IT-films. 
What do you think? 😄

**Comment by swapagarwal** [comment]
Hi Aleksandr! Your collection is great!
However, I'm curating inspiring content only. So my list contains movie scenes which are inspiring and not the full movie. 😇
