### ISSUE TITLE
Songs: Add Genius links

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/awesome-inspiration#8]

**Comment by till-tomorrow** [comment]
https://github.com/till-tomorrow/From-Project-to-Product/blob/master/README.md

I have created a repo to help people find projects that could be turned to a product. Contributing to such projects would definitely inspire them to work hard to get their projects live.

**Comment by jahway603** [comment]
Genius requires a paid subscription to listen to the whole song.
